build:neon-user-lts-deb:
  image: kdeneon/plasma:user-lts
  stage: build
  before_script:
    - sudo apt-get update -y
    - sudo apt-get install -y git cmake g++ extra-cmake-modules gettext qtbase5-dev libkf5xmlgui-dev libkf5i18n-dev libkf5kio-dev libkf5textwidgets-dev libkf5notifications-dev libkf5filemetadata-dev libqt5dbus5

  script:
    - cmake -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix` -DCMAKE_BUILD_TYPE=Release .
    - make -j`nproc`
    - cpack -G DEB -R 0.1.0-neon-user-lts
  artifacts:
    paths:
      - plasma-appimage-integration*.deb

build:arch_pkg:
  image: archlinux/base
  stage: build
  before_script:
    - pacman -Sy --noconfirm base-devel cmake git kf5 kdelibs4support
    - useradd build
  script:
    - mkdir build
    - chmod a+rwx build
    - cp -v dist/arch/* build
    - cd build && su build -c "makepkg"
    - mv plasma-appimage-integration*.pkg.tar.xz ..
  artifacts:
    paths:
      - plasma-appimage-integration*.pkg.tar.xz
