## AppImage
build:deb:
  image: ubuntu
  stage: build
  before_script:
    - apt-get update -y
    - apt-get install -y git cmake g++ libkf5xmlgui-dev libkf5i18n-dev libkf5kio-dev libkf5textwidgets-dev libkf5notifications-dev libkf5filemetadata-dev libqt5dbus5

  script:
    - cmake -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix` -DCMAKE_BUILD_TYPE=Release .
    - make -j`nproc`
    - cpack -G DEB
  artifacts:
    paths:
      - plasma-appimage-integration*.deb
